name: 統・Integration
on: [push, pull_request]
jobs:
  test:
    name: テスト・Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: システム・Package Lists
        run: sudo apt-get update
      - name: システム・Dependencies
        run: |
          sudo apt-get install -y build-essential libimlib2-dev libxft-dev \
          libfribidi-dev libxinerama-dev libx11-xcb-dev libxcb-res0-dev \
          ninja-build
      - name: システム・Compilation
        run: ninja
